version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGODB_USER: mongo
      MONGODB_PASS: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/mongo-db
    container_name: mongodb-instaclone
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
